"""empty message

Revision ID: 5130ac122b18
Revises: 4992f569b997
Create Date: 2025-07-14 15:01:51.278543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5130ac122b18'
down_revision = '4992f569b997'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taxes', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('taxes', 'is_active')
    # ### end Alembic commands ###
