"""empty message

Revision ID: 5c7466f9fa7a
Revises: 5130ac122b18
Create Date: 2025-07-14 17:18:56.610126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c7466f9fa7a'
down_revision = '5130ac122b18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_product_barcode', 'products', ['barcode'], unique=False)
    op.create_index('ix_product_shop_active', 'products', ['shop_id', 'is_active'], unique=False)
    op.create_index('ix_product_shop_combo', 'products', ['shop_id', 'combination_size'], unique=False)
    op.create_index('ix_product_shop_stock', 'products', ['shop_id', 'stock'], unique=False)
    op.create_index('ix_product_shop_supplier', 'products', ['shop_id', 'supplier_id'], unique=False)
    op.create_index('ix_product_sku', 'products', ['sku'], unique=False)
    op.create_index('ix_register_closed_at', 'register_sessions', ['closed_at'], unique=False)
    op.create_index('ix_register_closed_by', 'register_sessions', ['closed_by_id'], unique=False)
    op.create_index('ix_register_opened_at', 'register_sessions', ['opened_at'], unique=False)
    op.create_index('ix_register_opened_by', 'register_sessions', ['opened_by_id'], unique=False)
    op.create_index('ix_register_shop_closed', 'register_sessions', ['shop_id', 'closed_at'], unique=False)
    op.create_index('ix_sale_payment', 'sales', ['payment_method'], unique=False)
    op.create_index('ix_sale_session', 'sales', ['register_session_id'], unique=False)
    op.create_index('ix_sale_shop_date', 'sales', ['shop_id', 'date'], unique=False)
    op.create_index('ix_sale_shop_pay_date', 'sales', ['shop_id', 'payment_method', 'date'], unique=False)
    op.create_index('ix_sale_user', 'sales', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sale_user', table_name='sales')
    op.drop_index('ix_sale_shop_pay_date', table_name='sales')
    op.drop_index('ix_sale_shop_date', table_name='sales')
    op.drop_index('ix_sale_session', table_name='sales')
    op.drop_index('ix_sale_payment', table_name='sales')
    op.drop_index('ix_register_shop_closed', table_name='register_sessions')
    op.drop_index('ix_register_opened_by', table_name='register_sessions')
    op.drop_index('ix_register_opened_at', table_name='register_sessions')
    op.drop_index('ix_register_closed_by', table_name='register_sessions')
    op.drop_index('ix_register_closed_at', table_name='register_sessions')
    op.drop_index('ix_product_sku', table_name='products')
    op.drop_index('ix_product_shop_supplier', table_name='products')
    op.drop_index('ix_product_shop_stock', table_name='products')
    op.drop_index('ix_product_shop_combo', table_name='products')
    op.drop_index('ix_product_shop_active', table_name='products')
    op.drop_index('ix_product_barcode', table_name='products')
    # ### end Alembic commands ###
