"""removed some fiels from business

Revision ID: 1373affb265a
Revises: 928bb0b02bdf
Create Date: 2025-07-11 00:59:38.748350

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1373affb265a'
down_revision = '928bb0b02bdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'longitude')
    op.drop_column('businesses', 'banner_url')
    op.drop_column('businesses', 'latitude')
    op.drop_column('businesses', 'timezone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('timezone', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('businesses', sa.Column('latitude', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('businesses', sa.Column('banner_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('businesses', sa.Column('longitude', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
