"""empty message

Revision ID: 33259f5af143
Revises: 0345462a76a5
Create Date: 2024-10-31 19:59:58.638174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33259f5af143'
down_revision = '0345462a76a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('previous_stock', sa.Integer(), nullable=False),
    sa.Column('new_stock', sa.Integer(), nullable=False),
    sa.Column('adjustment_type', sa.Enum('addition', 'reduction', 'spoilage', 'theft', 'returned', 'inventory_adjustment', 'damage', name='adjustmenttype'), nullable=False),
    sa.Column('change_reason', sa.String(length=200), nullable=True),
    sa.Column('log_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_logs')
    # ### end Alembic commands ###
