"""empty message

Revision ID: 581507f81b46
Revises: 9500ad1b4ae6
Create Date: 2024-10-28 21:45:41.194639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '581507f81b46'
down_revision = '9500ad1b4ae6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'packet_size')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('packet_size', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
