"""empty message

Revision ID: 7d5526016982
Revises: 5894c50c16e1
Create Date: 2024-10-28 09:45:45.379751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d5526016982'
down_revision = '5894c50c16e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'unit_type')
    op.drop_column('products', 'bulk_quantity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('bulk_quantity', sa.FLOAT(), nullable=True))
    op.add_column('products', sa.Column('unit_type', sa.VARCHAR(length=6), nullable=False))
    # ### end Alembic commands ###
