"""empty message

Revision ID: 8477e832d24c
Revises: d811e2453f8d
Create Date: 2025-07-14 16:10:32.830849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8477e832d24c'
down_revision = 'd811e2453f8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taxes', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('taxes', 'is_active')
    # ### end Alembic commands ###
