"""empty message

Revision ID: 877cc7c6f106
Revises: 
Create Date: 2025-06-21 10:53:57.630595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '877cc7c6f106'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('change_type', sa.String(length=50), nullable=False),
    sa.Column('old_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('new_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('old_combo_size', sa.Integer(), nullable=True),
    sa.Column('old_combo_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('new_combo_size', sa.Integer(), nullable=True),
    sa.Column('new_combo_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('products', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('sales', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sales', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_column('sales', 'user_id')
    op.drop_column('products', 'created_at')
    op.drop_table('price_changes')
    # ### end Alembic commands ###
