"""initial migration

Revision ID: 928bb0b02bdf
Revises: 
Create Date: 2025-07-10 16:32:44.488042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '928bb0b02bdf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('display_name', sa.String(length=150), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('secondary_phone', sa.String(length=20), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('registration_number', sa.String(length=50), nullable=True),
    sa.Column('tax_identification', sa.String(length=50), nullable=True),
    sa.Column('business_type', sa.String(length=50), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('fiscal_year_start', sa.Date(), nullable=True),
    sa.Column('tax_rate', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', 'CLOSED', 'PENDING', name='businessstatus'), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('approval_notes', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('banner_url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('registration_number'),
    sa.UniqueConstraint('tax_identification')
    )
    op.create_index('ix_business_approved', 'businesses', ['is_approved'], unique=False)
    op.create_index('ix_business_status', 'businesses', ['status'], unique=False)
    op.create_index(op.f('ix_businesses_is_approved'), 'businesses', ['is_approved'], unique=False)
    op.create_index(op.f('ix_businesses_is_deleted'), 'businesses', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_businesses_name'), 'businesses', ['name'], unique=True)
    op.create_index(op.f('ix_businesses_status'), 'businesses', ['status'], unique=False)
    op.create_table('shops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shops_is_deleted'), 'shops', ['is_deleted'], unique=False)
    op.create_table('register_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('opening_cash', sa.Float(), nullable=False),
    sa.Column('closing_cash', sa.Float(), nullable=True),
    sa.Column('expected_cash', sa.Float(), nullable=True),
    sa.Column('discrepancy', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('opened_by_id', sa.Integer(), nullable=False),
    sa.Column('closed_by_id', sa.Integer(), nullable=True),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['closed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['opened_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_register_sessions_is_deleted'), 'register_sessions', ['is_deleted'], unique=False)
    op.create_index('ix_register_shop_date', 'register_sessions', ['shop_id', 'opened_at'], unique=False)
    op.create_table('taxes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('kra_code', sa.String(length=50), nullable=True),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'name', name='uq_tax_name_per_shop')
    )
    op.create_index(op.f('ix_taxes_is_deleted'), 'taxes', ['is_deleted'], unique=False)
    op.add_column('cart_items', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('cart_items', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('cart_items', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True))
    op.add_column('cart_items', sa.Column('total_price', sa.Float(), nullable=True))
    op.add_column('cart_items', sa.Column('unit_price', sa.Float(), nullable=True))
    op.add_column('cart_items', sa.Column('shop_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_cart_items_is_deleted'), 'cart_items', ['is_deleted'], unique=False)
    op.create_foreign_key(None, 'cart_items', 'shops', ['shop_id'], ['id'])
    op.add_column('categories', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('categories', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('categories', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True))
    op.add_column('categories', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('categories', sa.Column('position', sa.Integer(), nullable=True))
    op.add_column('categories', sa.Column('image_url', sa.String(length=255), nullable=True))
    op.add_column('categories', sa.Column('shop_id', sa.Integer(), nullable=True))
    op.drop_index('ix_categories_name', table_name='categories')
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=False)
    op.create_index(op.f('ix_categories_is_deleted'), 'categories', ['is_deleted'], unique=False)
    op.create_unique_constraint('uq_category_shop_name', 'categories', ['shop_id', 'name'])
    op.create_foreign_key(None, 'categories', 'shops', ['shop_id'], ['id'])
    op.add_column('expenses', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('expenses', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('expenses', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True))
    op.add_column('expenses', sa.Column('shop_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_expenses_is_deleted'), 'expenses', ['is_deleted'], unique=False)
    op.create_foreign_key(None, 'expenses', 'shops', ['shop_id'], ['id'])
    op.add_column('price_changes', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('price_changes', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('price_changes', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True))
    op.add_column('price_changes', sa.Column('shop_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_price_changes_is_deleted'), 'price_changes', ['is_deleted'], unique=False)
    op.create_foreign_key(None, 'price_changes', 'shops', ['shop_id'], ['id'])
    op.add_column('products', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('products', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True))
    op.add_column('products', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('barcode', sa.String(length=50), nullable=True))
    op.add_column('products', sa.Column('sku', sa.String(length=50), nullable=True))
    op.add_column('products', sa.Column('low_stock_threshold', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('image_url', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('products', sa.Column('is_featured', sa.Boolean(), nullable=True))
    op.add_column('products', sa.Column('shop_id', sa.Integer(), nullable=True))
    op.create_index('ix_product_name_shop', 'products', ['name', 'shop_id'], unique=False)
    op.create_index('ix_product_shop_category', 'products', ['shop_id', 'category_id'], unique=False)
    op.create_index(op.f('ix_products_is_deleted'), 'products', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_unique_constraint(None, 'products', ['sku'])
    op.create_unique_constraint(None, 'products', ['barcode'])
    op.create_foreign_key(None, 'products', 'shops', ['shop_id'], ['id'])
    op.add_column('sales', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('sales', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('sales', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True))
    op.add_column('sales', sa.Column('customer_phone', sa.String(length=20), nullable=True))
    op.add_column('sales', sa.Column('subtotal', sa.Float(), nullable=True))
    op.add_column('sales', sa.Column('tax', sa.Float(), nullable=True))
    op.add_column('sales', sa.Column('register_session_id', sa.Integer(), nullable=True))
    op.add_column('sales', sa.Column('shop_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_sales_is_deleted'), 'sales', ['is_deleted'], unique=False)
    op.create_foreign_key(None, 'sales', 'register_sessions', ['register_session_id'], ['id'])
    op.create_foreign_key(None, 'sales', 'shops', ['shop_id'], ['id'])
    op.add_column('stock_logs', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('stock_logs', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('stock_logs', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True))
    op.add_column('stock_logs', sa.Column('shop_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_stock_logs_is_deleted'), 'stock_logs', ['is_deleted'], unique=False)
    op.create_foreign_key(None, 'stock_logs', 'shops', ['shop_id'], ['id'])
    op.add_column('suppliers', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('suppliers', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('suppliers', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True))
    op.add_column('suppliers', sa.Column('shop_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_suppliers_is_deleted'), 'suppliers', ['is_deleted'], unique=False)
    op.create_foreign_key(None, 'suppliers', 'shops', ['shop_id'], ['id'])
    op.add_column('users', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(length=120), nullable=True))
    op.add_column('users', sa.Column('last_login', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('last_password_change', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('login_attempts', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('locked_until', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('business_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('shop_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('reset_token', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('reset_token_expires', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('email_verification_token', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('first_name', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('permissions', sa.JSON(), nullable=True))
    op.create_index('ix_user_business', 'users', ['business_id'], unique=False)
    op.create_index('ix_user_shop', 'users', ['shop_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_foreign_key(None, 'users', 'businesses', ['business_id'], ['id'])
    op.create_foreign_key(None, 'users', 'shops', ['shop_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('ix_user_shop', table_name='users')
    op.drop_index('ix_user_business', table_name='users')
    op.drop_column('users', 'permissions')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'email_verified')
    op.drop_column('users', 'email_verification_token')
    op.drop_column('users', 'reset_token_expires')
    op.drop_column('users', 'reset_token')
    op.drop_column('users', 'shop_id')
    op.drop_column('users', 'business_id')
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'login_attempts')
    op.drop_column('users', 'last_password_change')
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'email')
    op.drop_column('users', 'is_deleted')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_constraint(None, 'suppliers', type_='foreignkey')
    op.drop_index(op.f('ix_suppliers_is_deleted'), table_name='suppliers')
    op.drop_column('suppliers', 'shop_id')
    op.drop_column('suppliers', 'is_deleted')
    op.drop_column('suppliers', 'updated_at')
    op.drop_column('suppliers', 'created_at')
    op.drop_constraint(None, 'stock_logs', type_='foreignkey')
    op.drop_index(op.f('ix_stock_logs_is_deleted'), table_name='stock_logs')
    op.drop_column('stock_logs', 'shop_id')
    op.drop_column('stock_logs', 'is_deleted')
    op.drop_column('stock_logs', 'updated_at')
    op.drop_column('stock_logs', 'created_at')
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_index(op.f('ix_sales_is_deleted'), table_name='sales')
    op.drop_column('sales', 'shop_id')
    op.drop_column('sales', 'register_session_id')
    op.drop_column('sales', 'tax')
    op.drop_column('sales', 'subtotal')
    op.drop_column('sales', 'customer_phone')
    op.drop_column('sales', 'is_deleted')
    op.drop_column('sales', 'updated_at')
    op.drop_column('sales', 'created_at')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='unique')
    op.drop_constraint(None, 'products', type_='unique')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_is_deleted'), table_name='products')
    op.drop_index('ix_product_shop_category', table_name='products')
    op.drop_index('ix_product_name_shop', table_name='products')
    op.drop_column('products', 'shop_id')
    op.drop_column('products', 'is_featured')
    op.drop_column('products', 'is_active')
    op.drop_column('products', 'image_url')
    op.drop_column('products', 'low_stock_threshold')
    op.drop_column('products', 'sku')
    op.drop_column('products', 'barcode')
    op.drop_column('products', 'description')
    op.drop_column('products', 'is_deleted')
    op.drop_column('products', 'updated_at')
    op.drop_constraint(None, 'price_changes', type_='foreignkey')
    op.drop_index(op.f('ix_price_changes_is_deleted'), table_name='price_changes')
    op.drop_column('price_changes', 'shop_id')
    op.drop_column('price_changes', 'is_deleted')
    op.drop_column('price_changes', 'updated_at')
    op.drop_column('price_changes', 'created_at')
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_index(op.f('ix_expenses_is_deleted'), table_name='expenses')
    op.drop_column('expenses', 'shop_id')
    op.drop_column('expenses', 'is_deleted')
    op.drop_column('expenses', 'updated_at')
    op.drop_column('expenses', 'created_at')
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_constraint('uq_category_shop_name', 'categories', type_='unique')
    op.drop_index(op.f('ix_categories_is_deleted'), table_name='categories')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.create_index('ix_categories_name', 'categories', ['name'], unique=True)
    op.drop_column('categories', 'shop_id')
    op.drop_column('categories', 'image_url')
    op.drop_column('categories', 'position')
    op.drop_column('categories', 'is_active')
    op.drop_column('categories', 'is_deleted')
    op.drop_column('categories', 'updated_at')
    op.drop_column('categories', 'created_at')
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.drop_index(op.f('ix_cart_items_is_deleted'), table_name='cart_items')
    op.drop_column('cart_items', 'shop_id')
    op.drop_column('cart_items', 'unit_price')
    op.drop_column('cart_items', 'total_price')
    op.drop_column('cart_items', 'is_deleted')
    op.drop_column('cart_items', 'updated_at')
    op.drop_column('cart_items', 'created_at')
    op.drop_index(op.f('ix_taxes_is_deleted'), table_name='taxes')
    op.drop_table('taxes')
    op.drop_index('ix_register_shop_date', table_name='register_sessions')
    op.drop_index(op.f('ix_register_sessions_is_deleted'), table_name='register_sessions')
    op.drop_table('register_sessions')
    op.drop_index(op.f('ix_shops_is_deleted'), table_name='shops')
    op.drop_table('shops')
    op.drop_index(op.f('ix_businesses_status'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_name'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_is_deleted'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_is_approved'), table_name='businesses')
    op.drop_index('ix_business_status', table_name='businesses')
    op.drop_index('ix_business_approved', table_name='businesses')
    op.drop_table('businesses')
    # ### end Alembic commands ###
