"""number format changes

Revision ID: b374a0c6d259
Revises: 1373affb265a
Create Date: 2025-07-11 01:15:43.908708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b374a0c6d259'
down_revision = '1373affb265a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('timezone', sa.String(length=50), nullable=True))
    op.add_column('businesses', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('businesses', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('businesses', sa.Column('banner_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'banner_url')
    op.drop_column('businesses', 'longitude')
    op.drop_column('businesses', 'latitude')
    op.drop_column('businesses', 'timezone')
    # ### end Alembic commands ###
