"""empty message

Revision ID: f39184560399
Revises: b374a0c6d259
Create Date: 2025-07-12 13:02:01.744335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f39184560399'
down_revision = 'b374a0c6d259'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_product_sale', table_name='cart_items')
    op.create_index(op.f('ix_cart_items_product_id'), 'cart_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_cart_items_sale_id'), 'cart_items', ['sale_id'], unique=False)
    op.create_index('ix_cartitem_product_sale', 'cart_items', ['product_id', 'sale_id'], unique=False)
    op.create_index('ix_cartitem_sale_product', 'cart_items', ['sale_id', 'product_id'], unique=False)
    op.create_index('ix_cartitem_shop_product', 'cart_items', ['shop_id', 'product_id'], unique=False)
    op.create_index('ix_cartitem_shop_sale', 'cart_items', ['shop_id', 'sale_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cartitem_shop_sale', table_name='cart_items')
    op.drop_index('ix_cartitem_shop_product', table_name='cart_items')
    op.drop_index('ix_cartitem_sale_product', table_name='cart_items')
    op.drop_index('ix_cartitem_product_sale', table_name='cart_items')
    op.drop_index(op.f('ix_cart_items_sale_id'), table_name='cart_items')
    op.drop_index(op.f('ix_cart_items_product_id'), table_name='cart_items')
    op.create_index('ix_product_sale', 'cart_items', ['product_id', 'sale_id'], unique=False)
    # ### end Alembic commands ###
