"""initial migration

Revision ID: d811e2453f8d
Revises: 
Create Date: 2025-07-13 19:47:50.188029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd811e2453f8d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shops', sa.Column('email', sa.String(length=150), nullable=True))
    
    # ✅ Fix existing NULLs before enforcing NOT NULL
    op.execute("UPDATE shops SET is_active = TRUE WHERE is_active IS NULL")
    
    # ✅ Now it's safe to enforce the NOT NULL constraint
    op.alter_column('shops', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    
    op.create_unique_constraint(None, 'shops', ['phone'])
    op.create_unique_constraint(None, 'shops', ['email'])
    # ### end Alembic commands ###
